# Generated by Django 5.2.6 on 2025-10-13 09:23

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_price_product_reorder_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_upload_path),
        ),
    ]
