# Generated by Django 5.2.6 on 2025-10-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGGED_IN', 'User Logged In'), ('COMPANY_CREATED', 'Company Created'), ('INVENTORY_ITEM_CREATED', 'Inventory Item Created'), ('INVENTORY_ITEM_UPDATED', 'Inventory Item Updated'), ('STOCK_LEVEL_ADJUSTED', 'Stock Level Adjusted')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
