# Generated by Django 5.2.6 on 2025-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGGED_IN', 'User Logged In'), ('COMPANY_CREATED', 'Company Created'), ('INVENTORY_ITEM_CREATED', 'Inventory Item Created'), ('INVENTORY_ITEM_UPDATED', 'Inventory Item Updated'), ('STOCK_LEVEL_ADJUSTED', 'Stock Level Adjusted'), ('STOCK_ADDED', 'Stock Added'), ('STOCK_REMOVED', 'Stock Removed'), ('STOCK_SET', 'Stock Quantity Set'), ('STOCK_TRANSFERRED', 'Stock Transferred')], max_length=50),
        ),
    ]
