# Generated by Django 5.2.6 on 2025-09-29 14:35

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the company.', max_length=255)),
                ('industry', models.CharField(help_text='The industry the company operates in.', max_length=100)),
                ('currency', models.CharField(help_text='The default currency code (e.g., USD, EUR).', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=company.models.company_logo_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.TextField(blank=True, help_text='An AI-generated summary of the business.')),
            ],
        ),
    ]
