# Generated by Django 5.2.6 on 2025-10-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.CharField(blank=True, default='Due on receipt', help_text='Default payment terms for invoices and quotes.', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_tax_name',
            field=models.CharField(blank=True, default='Tax', help_text='The default name for sales tax (e.g., VAT, GST).', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The default sales tax rate as a percentage (e.g., 18.5).', max_digits=5),
        ),
    ]
