# Generated by Django 5.2.6 on 2025-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_payment_terms_company_sales_tax_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
