# Generated by Django 5.2.6 on 2025-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brand_color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Primary brand color extracted from logo (hex format, e.g., #3B82F6).', max_length=7),
        ),
    ]
