# Generated by Django 5.2.6 on 2025-10-15 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_company_onboarding_complete'),
        ('inventory', '0005_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(help_text='Unique quote identifier', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('INVOICED', 'Invoiced')], default='DRAFT', max_length=20)),
                ('date_issued', models.DateField(help_text='Date the quote was created or sent')),
                ('expiration_date', models.DateField(help_text='Date when the quote expires')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate as a percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the quote')),
                ('terms', models.TextField(blank=True, help_text='Payment terms and conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='inventory.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at time of quote', max_length=255)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU at time of quote', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of quote', max_digits=10)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_line_items', to='inventory.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='sales.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='sales_quote_quote_n_7b0af8_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='sales_quote_status_77c7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['date_issued'], name='sales_quote_date_is_e45d3b_idx'),
        ),
    ]
