# Generated by Django 5.2.6 on 2025-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_stock_reduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='Date when the invoice was marked as paid', null=True),
        ),
    ]
